databaseChangeLog:
  - changeSet:
      id: add-values_roles-table
      author: BelitskyiOleksandr
      changes:
        - insert:
            tableName: roles
            columns:
              - column:
                  name: name
                  value: ROLE_ADMIN
        - insert:
            tableName: roles
            columns:
              - column:
                  name: name
                  value: ROLE_USER